########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud --control staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/GTD/Deploy+Process#DeployProcess-vellum
    - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
    # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
    - sr/es-alias # Sravan Nov 18
    - sr/cs-multiselect  # Sravan May 31
    - ce/bulk-case-search # Cal July 6
    #- sr/memoized-toggle # Sravan July 26
    - dmr/throttle-system-forms  # Danny Sept 24
    - smh/remove-extra-spinner-icons # Steph Oct 6
    - ml/remove-pickles-phonelog # Minha Oct 7
    - dependabot/npm_and_yarn/moment-2.29.1 # Amit Oct 8
    # - dependabot/pip/requirements/certifi-2021.10.8   # SK / Joel Oct 12
    - es/mobile-auth # Simon Nov 23
    - jm/elastic-modernize-mappings+sr/case-reindex-staging  # Joel Dec 3
    - jm/elastic-modernize-mappings  # Joel Dec 3
    - sr/case-reindex-staging # Sravan Oct 14
    - sr/datums  # sravan Dec 21
    - ml/remove-pickles-reports # Minha Jan 24
    - jls/drop-case-search-limit # Jenny Jan 31
    - do/compare-case-properties # Dominic Feb 2
    - ml/remove-pickles-user-importer # Minha Feb 2
    - mk/support-multibar-reports # MK Dec 14
    - mk/support-expanded-cols-in-mobile-ucr # MK Feb 2
    - ad/save-only-edited-fields-migration # Addison Feb 4
    - cs/SC-1882-shared-saved-reports-m # Charl Feb 8
    - smh/data-registry-reports-permissions # Steph Feb 8
    - gh/mrm/base # Graham Feb 8
    - smh/data-registry-reports-permissions-domain-choice-provider # Steph Feb 14
    - mjr/export-metrics # Matt Feb 14
    - gh/form-version-bug # Graham Feb 15
    - ap/restrict-expressions-ui # Amit Feb 16
    - gh/mrm/erm-includes-mrm # Graham Feb 17
    - gh/mrm/superuser # Graham Feb 18
    - gh/mrm/newly-linked-domain # Graham Feb 20
    - gh/erm/consolidate-enterprise-roles # Graham Feb 20
    - gh/pickles/motech # Graham Feb 22
    - jls/force-manual-action-per-command # Jenny Feb 22
    - cs/support-12674_check_permission_on_web_user # Charl Feb 23
submodules: { }
